# Rustfmt configuration for Composer project
# Only using stable features

# Edition and style
edition = "2021"
hard_tabs = false
tab_spaces = 4

# Line length and wrapping
max_width = 100

# Function and method formatting
fn_params_layout = "Tall"

# Spacing
use_small_heuristics = "Default"

# Trailing elements
match_block_trailing_comma = true

# Chain formatting
chain_width = 60
single_line_if_else_max_width = 50

# Newline formatting
newline_style = "Unix"

# Import organization
reorder_imports = true

# Advanced formatting
force_explicit_abi = true